# Generated by Django 4.2 on 2023-04-08 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('read_time', models.IntegerField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('hero_image', models.ImageField(blank=True, upload_to='blog/assets')),
                ('content', models.TextField()),
            ],
        ),
    ]
