# Generated by Django 4.2 on 2023-04-08 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(auto_created=True, default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
