# Generated by Django 4.2 on 2023-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
